import { readFileSync, writeFileSync } from 'node:fs';
import { env } from 'node:process';

const { npm_package_version: version } = env;
if (!version) throw new TypeError('Package version is not defined.');

const match = version.match(/^(\d+)\.(\d+)(?=\.\d+$)/);
if (!match) throw new Error('Package version does not match SemVer.');

const majorVersion = match[1] !== '0' ? match[1] : match[0];

const readMe =
	`<!-- Do not edit this file directly. Reference cli/README -->\n` +
	'\n' +
	readFileSync('cli/README/intro.md', { encoding: 'utf8' }).replace(
		'tools@version',
		`tools@${majorVersion}`
	) +
	'\n' +
	readFileSync('cli/README/modules.md', { encoding: 'utf8' });

writeFileSync('README.md', readMe);
