# https://docs.npmjs.com/trusted-publishers
# https://pnpm.io/continuous-integration

name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm publish --no-git-checks --access public
